server:
  port: 8762
spring:
  application:
    name: microservive-discovery-eureka-ha
  profiles:
    active: peer2
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/
