server:
  port: 8031
spring:
  application:
    name: microservice-hystrix-turbine
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka/
turbine:
  app-config: microservice-consumer-movie
  cluster-name-expression: "'default'"