server:
  port: 8761
spring:
  application:
    name: eureka-authenticating
  security:
    user:
      name: user
      password: password123
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/